spring:
  main:
    web-application-type: none
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../../.env[.properties]
      - classpath:application-storage.yml
  application:
    name: enjoytrip-worker
  datasource:
    url: ${ENJOYTRIP_DB_URL:jdbc:postgresql://localhost:5432/enjoytrip}
    username: ${ENJOYTRIP_DB_USER:ssafy}
    password: ${ENJOYTRIP_DB_PASSWORD:ssafy}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true