drop table if exists course_views cascade;
drop table if exists course_embeddings cascade;
drop table if exists member_profile_embeddings cascade;
drop table if exists note_tags cascade;
drop table if exists note_saves cascade;
drop table if exists notifications cascade;
drop table if exists attraction_popularity_stats cascade;
drop table if exists attraction_saves cascade;
drop table if exists attraction_ratings cascade;
drop table if exists course_tags cascade;
drop table if exists tags cascade;
drop table if exists attractions cascade;
drop table if exists friendships cascade;
drop table if exists course_saves cascade;
drop table if exists course_items cascade;
drop table if exists courses cascade;
drop table if exists notes cascade;
drop table if exists plan_items cascade;
drop table if exists plans cascade;
drop table if exists news_items cascade;
drop table if exists hotplaces cascade;
drop table if exists notices cascade;
drop table if exists boards cascade;
drop table if exists auth_logs cascade;
drop table if exists members cascade;

create table auth_logs (
    id bigint generated by default as identity primary key,
    member_id bigint not null,
    event_type varchar(20) not null,
    logged_at timestamp not null
);

create table boards (
    id varchar(128) primary key,
    title varchar(255) not null,
    content clob not null,
    author varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table hotplaces (
    id varchar(128) primary key,
    member_id bigint not null,
    title varchar(255) not null,
    type varchar(64) not null,
    visit_date varchar(32) not null,
    lat double precision not null,
    lng double precision not null,
    description clob,
    photo clob,
    created_at timestamp not null,
    updated_at timestamp
);

create table members (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    nickname varchar(30),
    email varchar(255) not null unique,
    password varchar(255) not null,
    profile_image_url varchar(512),
    profile_image_object_key varchar(512),
    role varchar(20) not null default 'USER',
    created_at timestamp not null,
    updated_at timestamp
);

create table notices (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content clob not null,
    author varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table plans (
    id varchar(128) primary key,
    member_id bigint not null,
    title varchar(255) not null,
    start_date varchar(32) not null,
    end_date varchar(32) not null,
    budget integer not null,
    note clob,
    route_items clob,
    created_at timestamp not null,
    updated_at timestamp
);

create table plan_items (
    id bigint generated by default as identity primary key,
    plan_id varchar(128) not null,
    attraction_id bigint not null,
    position integer not null,
    day integer not null default 1,
    memo clob,
    stay_minutes integer not null default 90,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (plan_id, position)
);

create table news_items (
    id varchar(128) primary key,
    title varchar(512) not null,
    link varchar(1024) not null,
    summary clob,
    source varchar(255),
    published_at varchar(100),
    created_at timestamp not null default current_timestamp
);

create table courses (
    id varchar(128) primary key,
    owner_member_id bigint not null,
    title varchar(120) not null,
    region_name varchar(100),
    date varchar(32),
    deleted_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp
);

create table notes (
    id bigint generated by default as identity primary key,
    author_member_id bigint not null,
    title varchar(100) not null,
    content clob not null,
    category varchar(30) not null default 'UNCATEGORIZED',
    visibility varchar(20) not null default 'PUBLIC',
    latitude double precision not null,
    longitude double precision not null,
    region_name varchar(100),
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    deleted_at timestamp
);

create table course_items (
    id bigint generated by default as identity primary key,
    course_id varchar(128) not null,
    item_type varchar(20) not null,
    attraction_id bigint,
    note_id bigint,
    position integer not null,
    distance_to_next integer,
    duration_to_next integer,
    created_at timestamp not null default current_timestamp,
    constraint uk_course_items_course_id_id unique (course_id, id),
    constraint uk_course_items_course_position unique (course_id, position),
    constraint chk_course_items_position check (position > 0),
    constraint chk_course_items_distance_to_next check (distance_to_next is null or distance_to_next >= 0),
    constraint chk_course_items_duration_to_next check (duration_to_next is null or duration_to_next >= 0),
    constraint chk_course_items_type check (item_type in ('ATTRACTION', 'NOTE')),
    constraint chk_course_items_target check (
        (item_type = 'ATTRACTION' and attraction_id is not null and note_id is null)
        or
        (item_type = 'NOTE' and attraction_id is null and note_id is not null)
    )
);

create table course_saves (
    id bigint generated by default as identity primary key,
    course_id varchar(128) not null,
    member_id bigint not null,
    created_at timestamp not null default current_timestamp,
    unique (course_id, member_id)
);

create table friendships (
    id bigint generated by default as identity primary key,
    requester_member_id bigint not null,
    addressee_member_id bigint not null,
    status varchar(20) not null default 'PENDING',
    requested_at timestamp not null default current_timestamp,
    responded_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp
);

create table notifications (
    id bigint generated by default as identity primary key,
    recipient_member_id bigint not null,
    type varchar(50) not null,
    reference_type varchar(50) not null,
    reference_id bigint not null,
    payload clob,
    read_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (recipient_member_id, type, reference_type, reference_id)
);

create table attractions (
    id bigint primary key,
    title varchar(255),
    addr1 varchar(512),
    addr2 varchar(512),
    zipcode varchar(20),
    tel varchar(100),
    first_image varchar(1024),
    first_image2 varchar(1024),
    read_count integer default 0,
    sido_code integer,
    gugun_code integer,
    latitude double precision,
    longitude double precision,
    mlevel varchar(20),
    content_type_id varchar(20),
    overview clob,
    status varchar(20) not null default 'ACTIVE',
    updated_at timestamp,
    deleted_at timestamp,
    duplicate_of_attraction_id bigint,
    duplicate_reason clob,
    created_at timestamp not null default current_timestamp
);

create table attraction_saves (
    id bigint generated by default as identity primary key,
    attraction_id bigint not null,
    member_id bigint not null,
    created_at timestamp not null default current_timestamp,
    unique (attraction_id, member_id)
);

create table attraction_ratings (
    id bigint generated by default as identity primary key,
    attraction_id bigint not null,
    member_id bigint not null,
    rating integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (attraction_id, member_id)
);

create table tags (
    id bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table course_tags (
    course_id varchar(128) not null,
    tag_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint pk_course_tags primary key (course_id, tag_id)
);

create table attraction_popularity_stats (
    attraction_id bigint primary key,
    save_count integer not null default 0,
    rating_count integer not null default 0,
    average_rating decimal(3, 2) not null default 0,
    updated_at timestamp not null default current_timestamp
);

create table note_saves (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    member_id bigint not null,
    created_at timestamp not null default current_timestamp,
    unique (note_id, member_id)
);

create table note_tags (
    id bigint generated by default as identity primary key,
    note_id bigint not null,
    tag_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint uk_note_tags_note_tag unique (note_id, tag_id)
);

create table member_profile_embeddings (
    id                  bigint generated by default as identity primary key,
    member_id           bigint not null,
    profile_description clob,
    embedding           clob,
    source_version      varchar(128) not null,
    source_hash         varchar(64)  not null,
    embedding_dimension integer not null,
    provider            varchar(64)  not null,
    model               varchar(128) not null,
    status              varchar(20)  not null,
    failure_code        varchar(128),
    failure_message     varchar(1000),
    attempt_count       integer not null default 0,
    last_attempted_at   timestamp,
    embedded_at         timestamp,
    created_at          timestamp not null default current_timestamp,
    updated_at          timestamp not null default current_timestamp,
    constraint uk_member_profile_embeddings_member unique (member_id)
);

create table course_embeddings (
    id                  bigint generated by default as identity primary key,
    course_id           varchar(128) not null,
    description         clob,
    embedding           clob,
    dominant_category   varchar(30),
    source_version      varchar(128) not null,
    source_hash         varchar(64)  not null,
    embedding_dimension integer not null,
    provider            varchar(64)  not null,
    model               varchar(128) not null,
    status              varchar(20)  not null,
    failure_code        varchar(128),
    failure_message     varchar(1000),
    attempt_count       integer not null default 0,
    last_attempted_at   timestamp,
    embedded_at         timestamp,
    created_at          timestamp not null default current_timestamp,
    updated_at          timestamp not null default current_timestamp,
    constraint uk_course_embeddings_course unique (course_id)
);

create table course_views (
    id        bigint generated by default as identity primary key,
    course_id varchar(128) not null,
    member_id bigint not null,
    viewed_at timestamp not null default current_timestamp
);
