drop table if exists notifications cascade;
drop table if exists attraction_popularity_stats cascade;
drop table if exists attraction_saves cascade;
drop table if exists attraction_ratings cascade;
drop table if exists attraction_tag_mappings cascade;
drop table if exists attraction_tags cascade;
drop table if exists attractions cascade;
drop table if exists friendships cascade;
drop table if exists courses cascade;
drop table if exists plan_items cascade;
drop table if exists plans cascade;
drop table if exists news_items cascade;
drop table if exists hotplaces cascade;
drop table if exists notices cascade;
drop table if exists boards cascade;
drop table if exists auth_logs cascade;
drop table if exists members cascade;

create table auth_logs (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null,
    event_type varchar(20) not null,
    logged_at timestamp not null
);

create table boards (
    id varchar(128) primary key,
    title varchar(255) not null,
    content clob not null,
    author varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table hotplaces (
    id varchar(128) primary key,
    user_id varchar(64) not null,
    title varchar(255) not null,
    type varchar(64) not null,
    visit_date varchar(32) not null,
    lat double precision not null,
    lng double precision not null,
    description clob,
    photo clob,
    created_at timestamp not null,
    updated_at timestamp
);

create table members (
    id bigint generated by default as identity primary key,
    user_id varchar(64) not null unique,
    name varchar(100) not null,
    nickname varchar(30),
    email varchar(255) not null unique,
    password varchar(255) not null,
    profile_image_url varchar(512),
    profile_image_object_key varchar(512),
    created_at timestamp not null,
    updated_at timestamp
);

create table notices (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    content clob not null,
    author varchar(64) not null,
    created_at timestamp not null,
    updated_at timestamp
);

create table plans (
    id varchar(128) primary key,
    user_id varchar(64) not null,
    title varchar(255) not null,
    start_date varchar(32) not null,
    end_date varchar(32) not null,
    budget integer not null,
    note clob,
    route_items clob,
    created_at timestamp not null,
    updated_at timestamp
);

create table plan_items (
    id bigint generated by default as identity primary key,
    plan_id varchar(128) not null,
    attraction_id bigint not null,
    position integer not null,
    day integer not null default 1,
    memo clob,
    stay_minutes integer not null default 90,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (plan_id, position)
);

create table news_items (
    id varchar(128) primary key,
    title varchar(512) not null,
    link varchar(1024) not null,
    summary clob,
    source varchar(255),
    published_at varchar(100),
    created_at timestamp not null default current_timestamp
);

create table courses (
    id varchar(128) primary key,
    owner_user_id varchar(64) not null,
    title varchar(120) not null,
    region_name varchar(100),
    visibility varchar(20) not null default 'PRIVATE',
    status varchar(20) not null default 'DRAFT',
    deleted_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp
);

create table friendships (
    id bigint generated by default as identity primary key,
    requester_user_id varchar(64) not null,
    addressee_user_id varchar(64) not null,
    status varchar(20) not null default 'PENDING',
    requested_at timestamp not null default current_timestamp,
    responded_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp
);

create table notifications (
    id bigint generated by default as identity primary key,
    recipient_user_id varchar(64) not null,
    type varchar(50) not null,
    reference_type varchar(50) not null,
    reference_id bigint not null,
    payload clob,
    read_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (recipient_user_id, type, reference_type, reference_id)
);

create table attractions (
    id bigint primary key,
    title varchar(255),
    created_at timestamp not null default current_timestamp
);

create table attraction_saves (
    id bigint generated by default as identity primary key,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp not null default current_timestamp,
    unique (attraction_id, user_id)
);

create table attraction_ratings (
    id bigint generated by default as identity primary key,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    rating integer not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp,
    unique (attraction_id, user_id)
);

create table attraction_tags (
    id bigint generated by default as identity primary key,
    name varchar(255) not null
);

create table attraction_tag_mappings (
    attraction_id bigint not null,
    tag_id bigint not null
);

create table attraction_popularity_stats (
    attraction_id bigint primary key,
    save_count integer not null default 0,
    rating_count integer not null default 0,
    average_rating decimal(3, 2) not null default 0,
    updated_at timestamp not null default current_timestamp
);
