CREATE TABLE note_tags (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    note_id    BIGINT NOT NULL,
    tag_id     BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_note_tags_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT fk_note_tags_tag  FOREIGN KEY (tag_id)  REFERENCES tags(id)  ON DELETE CASCADE,
    CONSTRAINT uk_note_tags_note_tag UNIQUE (note_id, tag_id)
);
CREATE INDEX idx_note_tags_note_id ON note_tags(note_id);
