-- Dongnepin backend consolidated baseline schema.
--
-- This migration is a disposable/local/dev baseline reset generated by the
-- dongnepin migration-cleanup phase. It intentionally replaces the previous
-- V1..V15 history for fresh databases. Databases that already have the old
-- flyway_schema_history entries must not be repaired/reset against this file
-- without explicit user approval and a backup/restore plan.

create extension if not exists postgis;
create extension if not exists vector;

create table auth_logs (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    event_type varchar(20) not null,
    logged_at timestamp(6) not null,
    primary key (id)
);

create table boards (
    id varchar(128) not null,
    title varchar(255) not null,
    content text not null,
    author varchar(64) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table hotplaces (
    id varchar(128) not null,
    user_id varchar(64) not null,
    title varchar(255) not null,
    type varchar(64) not null,
    visit_date varchar(32) not null,
    lat float(53) not null,
    lng float(53) not null,
    description text,
    photo text,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table members (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    name varchar(100) not null,
    nickname varchar(30),
    email varchar(255) not null,
    password varchar(255) not null,
    profile_image_url varchar(512),
    representative_latitude numeric(10, 7),
    representative_longitude numeric(10, 7),
    representative_region_name varchar(100),
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id),
    constraint uk_members_user_id unique (user_id),
    constraint uk_members_email unique (email),
    constraint chk_members_representative_latitude
        check (representative_latitude is null or representative_latitude between -90 and 90),
    constraint chk_members_representative_longitude
        check (representative_longitude is null or representative_longitude between -180 and 180),
    constraint chk_members_representative_location_pair
        check ((representative_latitude is null) = (representative_longitude is null))
);

create table notices (
    id bigint generated by default as identity,
    title varchar(255) not null,
    content text not null,
    author varchar(64) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table plans (
    id varchar(128) not null,
    user_id varchar(64) not null,
    title varchar(255) not null,
    start_date varchar(32) not null,
    end_date varchar(32) not null,
    budget integer not null,
    note text,
    route_items text,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table attractions (
    id bigint primary key,
    title varchar(255) not null,
    addr1 varchar(512),
    addr2 varchar(512),
    zipcode varchar(20),
    tel varchar(100),
    first_image varchar(1024),
    first_image2 varchar(1024),
    read_count integer default 0,
    sido_code integer,
    gugun_code integer,
    mlevel varchar(20),
    content_type_id varchar(20),
    overview text,
    location geometry(Point, 4326),
    created_at timestamp(6) not null default current_timestamp
);

create table ev_chargers (
    id serial primary key,
    stat_id varchar(100) not null,
    stat_nm varchar(255) not null,
    chger_id varchar(50),
    chger_type varchar(50),
    addr varchar(512),
    location_desc varchar(512),
    use_time varchar(255),
    busi_nm varchar(255),
    busi_call varchar(100),
    stat varchar(50),
    location geometry(Point, 4326),
    created_at timestamp(6) not null default current_timestamp,
    unique (stat_id, chger_id)
);

create table news_items (
    id varchar(128) primary key,
    title varchar(512) not null,
    link varchar(1024) not null,
    summary text,
    source varchar(255),
    published_at varchar(100),
    created_at timestamp(6) not null default current_timestamp
);

create table attraction_photos (
    id serial primary key,
    content_id bigint not null,
    origin_img_url varchar(1024) not null,
    small_img_url varchar(1024),
    img_name varchar(255),
    created_at timestamp(6) not null default current_timestamp,
    constraint fk_attraction_photos_attraction
        foreign key (content_id) references attractions(id) on delete cascade
);

create table sunrise_sunset (
    id serial primary key,
    loc_name varchar(100) not null,
    loc_date varchar(8) not null,
    sunrise varchar(10),
    sunset varchar(10),
    moonrise varchar(10),
    moonset varchar(10),
    created_at timestamp(6) not null default current_timestamp,
    unique (loc_name, loc_date)
);

create table attraction_favorites (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_favorites_attraction_user unique (attraction_id, user_id),
    constraint fk_attraction_favorites_attraction
        foreign key (attraction_id) references attractions (id) on delete cascade
);

create table attraction_ratings (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    rating integer not null,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint uk_attraction_ratings_attraction_user unique (attraction_id, user_id),
    constraint fk_attraction_ratings_attraction
        foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint chk_attraction_ratings_rating check (rating between 1 and 5)
);

create table attraction_tags (
    id bigint generated by default as identity,
    name varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_tags_name unique (name)
);

create table attraction_tag_mappings (
    attraction_id bigint not null,
    tag_id bigint not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (attraction_id, tag_id),
    constraint fk_attraction_tag_mappings_attraction
        foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint fk_attraction_tag_mappings_tag
        foreign key (tag_id) references attraction_tags (id) on delete cascade
);

create table plan_items (
    id bigint generated by default as identity,
    plan_id varchar(128) not null,
    attraction_id bigint not null,
    position integer not null,
    day integer not null default 1,
    memo text,
    stay_minutes integer not null default 90,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint fk_plan_items_plan foreign key (plan_id) references plans (id) on delete cascade,
    constraint fk_plan_items_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint uk_plan_items_plan_position unique (plan_id, position),
    constraint chk_plan_items_position check (position > 0),
    constraint chk_plan_items_day check (day > 0),
    constraint chk_plan_items_stay_minutes check (stay_minutes > 0)
);

create table BATCH_JOB_INSTANCE (
    JOB_INSTANCE_ID bigint not null primary key,
    VERSION bigint,
    JOB_NAME varchar(100) not null,
    JOB_KEY varchar(32) not null,
    constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
);

create table BATCH_JOB_EXECUTION (
    JOB_EXECUTION_ID bigint not null primary key,
    VERSION bigint,
    JOB_INSTANCE_ID bigint not null,
    CREATE_TIME timestamp not null,
    START_TIME timestamp default null,
    END_TIME timestamp default null,
    STATUS varchar(10),
    EXIT_CODE varchar(2500),
    EXIT_MESSAGE varchar(2500),
    LAST_UPDATED timestamp,
    constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID) references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

create table BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID bigint not null,
    PARAMETER_NAME varchar(100) not null,
    PARAMETER_TYPE varchar(100) not null,
    PARAMETER_VALUE varchar(2500),
    IDENTIFYING char(1) not null,
    constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

create table BATCH_STEP_EXECUTION (
    STEP_EXECUTION_ID bigint not null primary key,
    VERSION bigint not null,
    STEP_NAME varchar(100) not null,
    JOB_EXECUTION_ID bigint not null,
    CREATE_TIME timestamp not null,
    START_TIME timestamp default null,
    END_TIME timestamp default null,
    STATUS varchar(10),
    COMMIT_COUNT bigint,
    READ_COUNT bigint,
    FILTER_COUNT bigint,
    WRITE_COUNT bigint,
    READ_SKIP_COUNT bigint,
    WRITE_SKIP_COUNT bigint,
    PROCESS_SKIP_COUNT bigint,
    ROLLBACK_COUNT bigint,
    EXIT_CODE varchar(2500),
    EXIT_MESSAGE varchar(2500),
    LAST_UPDATED timestamp,
    constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

create table BATCH_STEP_EXECUTION_CONTEXT (
    STEP_EXECUTION_ID bigint not null primary key,
    SHORT_CONTEXT varchar(2500) not null,
    SERIALIZED_CONTEXT text,
    constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID) references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

create table BATCH_JOB_EXECUTION_CONTEXT (
    JOB_EXECUTION_ID bigint not null primary key,
    SHORT_CONTEXT varchar(2500) not null,
    SERIALIZED_CONTEXT text,
    constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID) references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

create sequence BATCH_STEP_EXECUTION_SEQ maxvalue 9223372036854775807 no cycle;
create sequence BATCH_JOB_EXECUTION_SEQ maxvalue 9223372036854775807 no cycle;
create sequence BATCH_JOB_SEQ maxvalue 9223372036854775807 no cycle;

create table attraction_embeddings (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    embedding vector(3072),
    embedding_input text,
    source_version varchar(128) not null,
    source_text_hash varchar(64) not null,
    embedding_dimension integer not null,
    provider varchar(64) not null,
    model varchar(128) not null,
    status varchar(20) not null,
    failure_code varchar(128),
    failure_message varchar(1000),
    attempt_count integer not null default 0,
    last_attempted_at timestamp(6),
    embedded_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_embeddings_attraction unique (attraction_id),
    constraint fk_attraction_embeddings_attraction foreign key (attraction_id) references attractions(id) on delete cascade,
    constraint chk_attraction_embeddings_status check (status in ('PENDING', 'EMBEDDED', 'FAILED')),
    constraint chk_attraction_embeddings_dimension check (embedding_dimension = 3072),
    constraint chk_attraction_embeddings_hash check (char_length(source_text_hash) = 64),
    constraint chk_attraction_embeddings_attempt_count check (attempt_count >= 0)
);

create table notes (
    id bigint generated by default as identity,
    author_user_id varchar(64) not null,
    title varchar(100) not null,
    content text not null,
    category varchar(30) not null default 'UNCATEGORIZED',
    visibility varchar(20) not null default 'PUBLIC',
    location geometry(Point, 4326) not null,
    latitude numeric(10, 7) not null,
    longitude numeric(10, 7) not null,
    region_name varchar(100),
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id),
    constraint fk_notes_author foreign key (author_user_id) references members (user_id),
    constraint chk_notes_category check (category in ('BEST', 'MUSIC', 'BOOK', 'MOVIE', 'TIP', 'TRANSIT_TIP', 'UNCATEGORIZED')),
    constraint chk_notes_visibility check (visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_notes_status check (status in ('ACTIVE', 'HIDDEN', 'DELETED')),
    constraint chk_notes_latitude check (latitude between -90 and 90),
    constraint chk_notes_longitude check (longitude between -180 and 180)
);

create table note_photos (
    id bigint generated by default as identity,
    note_id bigint not null,
    image_url varchar(1024) not null,
    position integer not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_photos_note foreign key (note_id) references notes (id) on delete cascade,
    constraint uk_note_photos_note_position unique (note_id, position),
    constraint chk_note_photos_position check (position > 0)
);

create table note_saves (
    id bigint generated by default as identity,
    note_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_saves_note foreign key (note_id) references notes (id) on delete cascade,
    constraint fk_note_saves_member foreign key (user_id) references members (user_id),
    constraint uk_note_saves_note_user unique (note_id, user_id)
);

create table note_reports (
    id bigint generated by default as identity,
    note_id bigint not null,
    reporter_user_id varchar(64) not null,
    reason varchar(50) not null,
    detail text,
    status varchar(20) not null default 'OPEN',
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_reports_note foreign key (note_id) references notes (id) on delete cascade,
    constraint fk_note_reports_reporter foreign key (reporter_user_id) references members (user_id),
    constraint uk_note_reports_note_reporter unique (note_id, reporter_user_id),
    constraint chk_note_reports_status check (status in ('OPEN', 'REVIEWED', 'REJECTED'))
);

create table courses (
    id varchar(128) not null,
    owner_user_id varchar(64) not null,
    title varchar(120) not null,
    region_name varchar(100),
    visibility varchar(20) not null default 'PRIVATE',
    status varchar(20) not null default 'DRAFT',
    description text,
    cover_image_url varchar(1024),
    share_image_url varchar(1024),
    route_line geometry(LineString, 4326),
    started_at timestamp(6),
    completed_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id),
    constraint fk_courses_owner foreign key (owner_user_id) references members (user_id),
    constraint chk_courses_visibility check (visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_courses_status check (status in ('DRAFT', 'READY', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED'))
);

create table course_items (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    item_type varchar(20) not null,
    attraction_id bigint,
    note_id bigint,
    position integer not null,
    day integer not null default 1,
    memo text,
    stay_minutes integer,
    completed_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_items_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_items_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint fk_course_items_note foreign key (note_id) references notes (id) on delete cascade,
    constraint uk_course_items_course_position unique (course_id, position),
    constraint chk_course_items_position check (position > 0),
    constraint chk_course_items_day check (day > 0),
    constraint chk_course_items_stay_minutes check (stay_minutes is null or stay_minutes > 0),
    constraint chk_course_items_type check (item_type in ('ATTRACTION', 'NOTE')),
    constraint chk_course_items_target check (
        (item_type = 'ATTRACTION' and attraction_id is not null and note_id is null)
        or
        (item_type = 'NOTE' and attraction_id is null and note_id is not null)
    )
);

create table course_saves (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_saves_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_saves_member foreign key (user_id) references members (user_id),
    constraint uk_course_saves_course_user unique (course_id, user_id)
);

create table course_reports (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    reporter_user_id varchar(64) not null,
    reason varchar(50) not null,
    detail text,
    status varchar(20) not null default 'OPEN',
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_reports_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_reports_reporter foreign key (reporter_user_id) references members (user_id),
    constraint uk_course_reports_course_reporter unique (course_id, reporter_user_id),
    constraint chk_course_reports_status check (status in ('OPEN', 'REVIEWED', 'REJECTED'))
);

create table friendships (
    id bigint generated by default as identity,
    requester_user_id varchar(64) not null,
    addressee_user_id varchar(64) not null,
    status varchar(20) not null default 'PENDING',
    requested_at timestamp(6) not null default current_timestamp,
    responded_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint fk_friendships_requester foreign key (requester_user_id) references members (user_id),
    constraint fk_friendships_addressee foreign key (addressee_user_id) references members (user_id),
    constraint chk_friendships_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'DELETED')),
    constraint chk_friendships_distinct_members check (requester_user_id <> addressee_user_id)
);

create table member_settings (
    user_id varchar(64) not null,
    default_note_visibility varchar(20) not null default 'PUBLIC',
    default_course_visibility varchar(20) not null default 'PRIVATE',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (user_id),
    constraint fk_member_settings_member foreign key (user_id) references members (user_id) on delete cascade,
    constraint chk_member_settings_note_visibility check (default_note_visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_member_settings_course_visibility check (default_course_visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE'))
);

create table attraction_popularity_stats (
    attraction_id bigint not null,
    favorite_count integer not null default 0,
    rating_count integer not null default 0,
    average_rating numeric(3, 2) not null default 0,
    view_count integer not null default 0,
    course_add_count integer not null default 0,
    popularity_score numeric(12, 4) not null default 0,
    updated_at timestamp(6) not null default current_timestamp,
    primary key (attraction_id),
    constraint fk_attraction_popularity_stats_attraction
        foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint chk_attraction_popularity_stats_favorite_count check (favorite_count >= 0),
    constraint chk_attraction_popularity_stats_rating_count check (rating_count >= 0),
    constraint chk_attraction_popularity_stats_average_rating check (average_rating between 0 and 5),
    constraint chk_attraction_popularity_stats_view_count check (view_count >= 0),
    constraint chk_attraction_popularity_stats_course_add_count check (course_add_count >= 0),
    constraint chk_attraction_popularity_stats_popularity_score check (popularity_score >= 0)
);

create table notification_outbox (
    id bigint generated by default as identity,
    event_type varchar(50) not null,
    recipient_user_id varchar(64) not null,
    aggregate_type varchar(50) not null,
    aggregate_id bigint not null,
    payload jsonb,
    status varchar(20) not null default 'PENDING',
    attempt_count integer not null default 0,
    last_error varchar(1000),
    created_at timestamp(6) not null default current_timestamp,
    processed_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint fk_notification_outbox_recipient foreign key (recipient_user_id) references members (user_id),
    constraint chk_notification_outbox_event_type check (event_type in ('FRIEND_REQUEST_RECEIVED')),
    constraint chk_notification_outbox_aggregate_type check (aggregate_type in ('FRIENDSHIP')),
    constraint chk_notification_outbox_status check (status in ('PENDING', 'PROCESSED', 'FAILED')),
    constraint chk_notification_outbox_attempt_count check (attempt_count >= 0)
);

create table notifications (
    id bigint generated by default as identity,
    recipient_user_id varchar(64) not null,
    type varchar(50) not null,
    reference_type varchar(50) not null,
    reference_id bigint not null,
    payload jsonb,
    read_at timestamp(6),
    outbox_event_id bigint not null,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint fk_notifications_recipient foreign key (recipient_user_id) references members (user_id),
    constraint fk_notifications_outbox foreign key (outbox_event_id) references notification_outbox (id),
    constraint uk_notifications_outbox_event unique (outbox_event_id),
    constraint chk_notifications_type check (type in ('FRIEND_REQUEST_RECEIVED')),
    constraint chk_notifications_reference_type check (reference_type in ('FRIENDSHIP'))
);

create index idx_auth_logs_user_id on auth_logs (user_id);
create index idx_hotplaces_user_id_created_at on hotplaces (user_id, created_at desc);
create index idx_plans_user_id_created_at on plans (user_id, created_at desc);
create index idx_attractions_location on attractions using gist (location);
create index idx_ev_chargers_location on ev_chargers using gist (location);
create index idx_attractions_area on attractions (sido_code, gugun_code);
create index idx_attraction_photos_content_id on attraction_photos (content_id);
create index idx_sunrise_sunset_loc on sunrise_sunset (loc_name, loc_date);
create index idx_attraction_favorites_attraction on attraction_favorites (attraction_id);
create index idx_attraction_ratings_attraction on attraction_ratings (attraction_id);
create index idx_attraction_tag_mappings_tag on attraction_tag_mappings (tag_id);
create index idx_plan_items_plan_position on plan_items (plan_id, position);
create index idx_attraction_embeddings_status on attraction_embeddings (status);
create index idx_attraction_embeddings_source on attraction_embeddings (source_version, source_text_hash);
create index idx_notes_location on notes using gist (location);
create index idx_notes_recent on notes (created_at desc);
create index idx_notes_author_created on notes (author_user_id, created_at desc);
create index idx_notes_visibility_status_created on notes (visibility, status, created_at desc);
create index idx_notes_category_created on notes (category, created_at desc);
create index idx_note_saves_user_created on note_saves (user_id, created_at desc);
create index idx_note_reports_status_created on note_reports (status, created_at desc);
create index idx_courses_owner_created on courses (owner_user_id, created_at desc);
create index idx_courses_visibility_status_created on courses (visibility, status, created_at desc);
create index idx_courses_region_created on courses (region_name, created_at desc);
create index idx_courses_route_line on courses using gist (route_line);
create index idx_course_items_course_position on course_items (course_id, position);
create index idx_course_items_attraction on course_items (attraction_id);
create index idx_course_items_note on course_items (note_id);
create index idx_course_saves_user_created on course_saves (user_id, created_at desc);
create index idx_course_reports_status_created on course_reports (status, created_at desc);
create unique index uk_friendships_user_pair_active on friendships (least(requester_user_id, addressee_user_id), greatest(requester_user_id, addressee_user_id)) where status in ('PENDING', 'ACCEPTED');
create index idx_friendships_requester_status on friendships (requester_user_id, status);
create index idx_friendships_addressee_status on friendships (addressee_user_id, status);
create index idx_attraction_popularity_stats_score on attraction_popularity_stats (popularity_score desc, attraction_id);
create index idx_notifications_recipient_created_at on notifications (recipient_user_id, created_at desc);
create index idx_notifications_recipient_read_at on notifications (recipient_user_id, read_at);
create index idx_notification_outbox_status_created_at on notification_outbox (status, created_at);
