CREATE TABLE member_profile_embeddings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id           BIGINT NOT NULL,
    profile_description TEXT,
    embedding           vector(1536),
    source_version      VARCHAR(128) NOT NULL,
    source_hash         VARCHAR(64)  NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    provider            VARCHAR(64)  NOT NULL,
    model               VARCHAR(128) NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    failure_code        VARCHAR(128),
    failure_message     VARCHAR(1000),
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    last_attempted_at   TIMESTAMP(6),
    embedded_at         TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_member_profile_embeddings_member UNIQUE (member_id),
    CONSTRAINT fk_member_profile_embeddings_member
        FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT chk_member_profile_embeddings_status
        CHECK (status IN ('PENDING', 'EMBEDDED', 'FAILED')),
    CONSTRAINT chk_member_profile_embeddings_dimension
        CHECK (embedding_dimension = 1536)
);
CREATE INDEX idx_member_profile_embeddings_status ON member_profile_embeddings(status);
