CREATE TABLE course_embeddings (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id           VARCHAR(128) NOT NULL,
    description         TEXT,
    embedding           vector(1536),
    dominant_category   VARCHAR(30),
    source_version      VARCHAR(128) NOT NULL,
    source_hash         VARCHAR(64)  NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    provider            VARCHAR(64)  NOT NULL,
    model               VARCHAR(128) NOT NULL,
    status              VARCHAR(20)  NOT NULL,
    failure_code        VARCHAR(128),
    failure_message     VARCHAR(1000),
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    last_attempted_at   TIMESTAMP(6),
    embedded_at         TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_course_embeddings_course UNIQUE (course_id),
    CONSTRAINT fk_course_embeddings_course
        FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT chk_course_embeddings_status
        CHECK (status IN ('PENDING', 'EMBEDDED', 'FAILED')),
    CONSTRAINT chk_course_embeddings_dimension
        CHECK (embedding_dimension = 1536)
);
CREATE INDEX idx_course_embeddings_status ON course_embeddings(status);
