CREATE TABLE course_views (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id VARCHAR(128) NOT NULL,
    member_id BIGINT NOT NULL,
    viewed_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_course_views_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_course_views_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
);
CREATE INDEX idx_course_views_member_viewed ON course_views(member_id, viewed_at DESC);
