create table attraction_saves (
    id bigint generated by default as identity primary key,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    constraint fk_attraction_saves_attraction
        foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint fk_attraction_saves_member
        foreign key (user_id) references members (user_id),
    constraint uk_attraction_saves_attraction_user unique (attraction_id, user_id)
);

create index idx_attraction_saves_attraction on attraction_saves (attraction_id);
create index idx_attraction_saves_user_created on attraction_saves (user_id, created_at desc);

alter table attraction_popularity_stats
    add column save_count integer not null default 0;

alter table attraction_popularity_stats
    add constraint chk_attraction_popularity_stats_save_count check (save_count >= 0);

insert into attraction_popularity_stats (attraction_id, favorite_count, updated_at)
select attraction_id,
       count(*)::integer as favorite_count,
       current_timestamp
from attraction_favorites
group by attraction_id
on conflict (attraction_id)
do update set favorite_count = excluded.favorite_count,
              updated_at = current_timestamp;
