create table courses (
    id varchar(128) not null,
    owner_user_id varchar(64) not null,
    title varchar(120) not null,
    region_name varchar(100),
    visibility varchar(20) not null default 'PRIVATE',
    status varchar(20) not null default 'DRAFT',
    description text,
    cover_image_url varchar(1024),
    share_image_url varchar(1024),
    route_line geometry(LineString, 4326),
    started_at timestamp(6),
    completed_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id),
    constraint fk_courses_owner foreign key (owner_user_id) references members (user_id),
    constraint chk_courses_visibility check (visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_courses_status check (status in ('DRAFT', 'READY', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED'))
);

create table course_items (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    item_type varchar(20) not null,
    attraction_id bigint,
    note_id bigint,
    position integer not null,
    day integer not null default 1,
    memo text,
    stay_minutes integer,
    completed_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_items_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_items_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint fk_course_items_note foreign key (note_id) references notes (id) on delete cascade,
    constraint uk_course_items_course_position unique (course_id, position),
    constraint chk_course_items_position check (position > 0),
    constraint chk_course_items_day check (day > 0),
    constraint chk_course_items_stay_minutes check (stay_minutes is null or stay_minutes > 0),
    constraint chk_course_items_type check (item_type in ('ATTRACTION', 'NOTE')),
    constraint chk_course_items_target check (
        (item_type = 'ATTRACTION' and attraction_id is not null and note_id is null)
        or
        (item_type = 'NOTE' and attraction_id is null and note_id is not null)
    )
);

create table course_saves (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_saves_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_saves_member foreign key (user_id) references members (user_id),
    constraint uk_course_saves_course_user unique (course_id, user_id)
);

create table course_reports (
    id bigint generated by default as identity,
    course_id varchar(128) not null,
    reporter_user_id varchar(64) not null,
    reason varchar(50) not null,
    detail text,
    status varchar(20) not null default 'OPEN',
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_course_reports_course foreign key (course_id) references courses (id) on delete cascade,
    constraint fk_course_reports_reporter foreign key (reporter_user_id) references members (user_id),
    constraint uk_course_reports_course_reporter unique (course_id, reporter_user_id),
    constraint chk_course_reports_status check (status in ('OPEN', 'REVIEWED', 'REJECTED'))
);

create index idx_courses_owner_created on courses (owner_user_id, created_at desc);
create index idx_courses_visibility_status_created on courses (visibility, status, created_at desc);
create index idx_courses_region_created on courses (region_name, created_at desc);
create index idx_courses_route_line on courses using gist (route_line);
create index idx_course_items_course_position on course_items (course_id, position);
create index idx_course_items_attraction on course_items (attraction_id);
create index idx_course_items_note on course_items (note_id);
create index idx_course_saves_user_created on course_saves (user_id, created_at desc);
create index idx_course_reports_status_created on course_reports (status, created_at desc);
