create table friendships (
    id bigint generated by default as identity,
    requester_user_id varchar(64) not null,
    addressee_user_id varchar(64) not null,
    status varchar(20) not null default 'PENDING',
    requested_at timestamp(6) not null default current_timestamp,
    responded_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint fk_friendships_requester foreign key (requester_user_id) references members (user_id),
    constraint fk_friendships_addressee foreign key (addressee_user_id) references members (user_id),
    constraint chk_friendships_status check (status in ('PENDING', 'ACCEPTED', 'REJECTED', 'DELETED')),
    constraint chk_friendships_distinct_members check (requester_user_id <> addressee_user_id)
);

create table member_settings (
    user_id varchar(64) not null,
    default_note_visibility varchar(20) not null default 'PUBLIC',
    default_course_visibility varchar(20) not null default 'PRIVATE',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (user_id),
    constraint fk_member_settings_member foreign key (user_id) references members (user_id) on delete cascade,
    constraint chk_member_settings_note_visibility check (default_note_visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_member_settings_course_visibility check (default_course_visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE'))
);

insert into member_settings (user_id)
select user_id
from members;

create unique index uk_friendships_user_pair_active on friendships (least(requester_user_id, addressee_user_id), greatest(requester_user_id, addressee_user_id)) where status in ('PENDING', 'ACCEPTED');
create index idx_friendships_requester_status on friendships (requester_user_id, status);
create index idx_friendships_addressee_status on friendships (addressee_user_id, status);
