create table notification_outbox (
    id bigint generated by default as identity,
    event_type varchar(50) not null,
    recipient_user_id varchar(64) not null,
    aggregate_type varchar(50) not null,
    aggregate_id bigint not null,
    payload jsonb,
    status varchar(20) not null default 'PENDING',
    attempt_count integer not null default 0,
    last_error varchar(1000),
    created_at timestamp(6) not null default current_timestamp,
    processed_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint fk_notification_outbox_recipient foreign key (recipient_user_id) references members (user_id),
    constraint chk_notification_outbox_event_type check (event_type in ('FRIEND_REQUEST_RECEIVED')),
    constraint chk_notification_outbox_aggregate_type check (aggregate_type in ('FRIENDSHIP')),
    constraint chk_notification_outbox_status check (status in ('PENDING', 'PROCESSED', 'FAILED')),
    constraint chk_notification_outbox_attempt_count check (attempt_count >= 0)
);

create table notifications (
    id bigint generated by default as identity,
    recipient_user_id varchar(64) not null,
    type varchar(50) not null,
    reference_type varchar(50) not null,
    reference_id bigint not null,
    payload jsonb,
    read_at timestamp(6),
    outbox_event_id bigint not null,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint fk_notifications_recipient foreign key (recipient_user_id) references members (user_id),
    constraint fk_notifications_outbox foreign key (outbox_event_id) references notification_outbox (id),
    constraint uk_notifications_outbox_event unique (outbox_event_id),
    constraint chk_notifications_type check (type in ('FRIEND_REQUEST_RECEIVED')),
    constraint chk_notifications_reference_type check (reference_type in ('FRIENDSHIP'))
);

create index idx_notifications_recipient_created_at on notifications (recipient_user_id, created_at desc);
create index idx_notifications_recipient_read_at on notifications (recipient_user_id, read_at);
create index idx_notification_outbox_status_created_at on notification_outbox (status, created_at);
