create table notes (
    id bigint generated by default as identity,
    author_user_id varchar(64) not null,
    title varchar(100) not null,
    content text not null,
    category varchar(30) not null default 'UNCATEGORIZED',
    visibility varchar(20) not null default 'PUBLIC',
    location geometry(Point, 4326) not null,
    latitude numeric(10, 7) not null,
    longitude numeric(10, 7) not null,
    region_name varchar(100),
    status varchar(20) not null default 'ACTIVE',
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    deleted_at timestamp(6),
    primary key (id),
    constraint fk_notes_author foreign key (author_user_id) references members (user_id),
    constraint chk_notes_category check (category in ('BEST', 'MUSIC', 'BOOK', 'MOVIE', 'TIP', 'TRANSIT_TIP', 'UNCATEGORIZED')),
    constraint chk_notes_visibility check (visibility in ('PUBLIC', 'FRIENDS', 'PRIVATE')),
    constraint chk_notes_status check (status in ('ACTIVE', 'HIDDEN', 'DELETED')),
    constraint chk_notes_latitude check (latitude between -90 and 90),
    constraint chk_notes_longitude check (longitude between -180 and 180)
);

create table note_photos (
    id bigint generated by default as identity,
    note_id bigint not null,
    image_url varchar(1024) not null,
    position integer not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_photos_note foreign key (note_id) references notes (id) on delete cascade,
    constraint uk_note_photos_note_position unique (note_id, position),
    constraint chk_note_photos_position check (position > 0)
);

create table note_saves (
    id bigint generated by default as identity,
    note_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_saves_note foreign key (note_id) references notes (id) on delete cascade,
    constraint fk_note_saves_member foreign key (user_id) references members (user_id),
    constraint uk_note_saves_note_user unique (note_id, user_id)
);

create table note_reports (
    id bigint generated by default as identity,
    note_id bigint not null,
    reporter_user_id varchar(64) not null,
    reason varchar(50) not null,
    detail text,
    status varchar(20) not null default 'OPEN',
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_note_reports_note foreign key (note_id) references notes (id) on delete cascade,
    constraint fk_note_reports_reporter foreign key (reporter_user_id) references members (user_id),
    constraint uk_note_reports_note_reporter unique (note_id, reporter_user_id),
    constraint chk_note_reports_status check (status in ('OPEN', 'REVIEWED', 'REJECTED'))
);

create index idx_notes_location on notes using gist (location);
create index idx_notes_recent on notes (created_at desc);
create index idx_notes_author_created on notes (author_user_id, created_at desc);
create index idx_notes_visibility_status_created on notes (visibility, status, created_at desc);
create index idx_notes_category_created on notes (category, created_at desc);
create index idx_note_saves_user_created on note_saves (user_id, created_at desc);
create index idx_note_reports_status_created on note_reports (status, created_at desc);
